# Generated by Django 4.0.10 on 2023-04-24 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 14, 22, 53, 331852, tzinfo=utc)),
        ),
    ]
