# Generated by Django 4.0.10 on 2023-04-24 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
