# Generated by Django 4.0.10 on 2023-04-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
