# Generated by Django 4.0.10 on 2023-04-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer', models.EmailField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=20)),
                ('descriptions', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('photo1', models.ImageField(upload_to='projects/')),
                ('photo2', models.ImageField(upload_to='projects/')),
                ('photo3', models.ImageField(upload_to='projects/')),
            ],
        ),
    ]
