# Generated by Django 4.0.10 on 2023-04-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersProjects', '0002_projects_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
