# Generated by Django 4.0.10 on 2023-04-23 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmersProjects', '0003_projects_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='slug',
        ),
    ]
