# Generated by Django 4.0.10 on 2023-04-23 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmersProjects', '0004_remove_projects_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
