# Generated by Django 4.0.10 on 2023-04-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmersProjects', '0005_projects_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectID', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('farmer', models.EmailField(max_length=255)),
                ('customer', models.EmailField(max_length=255)),
                ('book_date', models.DateField(max_length=255)),
            ],
        ),
    ]
