# Generated by Django 4.0.10 on 2023-04-24 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmersProjects', '0006_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
