# Generated by Django 4.0.10 on 2023-04-24 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('farmersProjects', '0007_alter_booking_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 24, 14, 22, 53, 329143, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 14, 22, 53, 329143, tzinfo=utc)),
        ),
    ]
