# Generated by Django 4.0.10 on 2023-04-24 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmersProjects', '0008_alter_booking_book_date_alter_projects_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
